//
// EventInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EventInfo: Codable, JSONEncodable, Hashable {

    public var date: String?
    public var place: Location?

    public init(date: String? = nil, place: Location? = nil) {
        self.date = date
        self.place = place
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case place
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(place, forKey: .place)
    }
}

