//
// ItemLinks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ItemLinks: Codable, JSONEncodable, Hashable {

    public var rel: String?
    public var href: String?
    public var action: String?
    public var types: String?

    public init(rel: String? = nil, href: String? = nil, action: String? = nil, types: String? = nil) {
        self.rel = rel
        self.href = href
        self.action = action
        self.types = types
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rel
        case href
        case action
        case types
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rel, forKey: .rel)
        try container.encodeIfPresent(href, forKey: .href)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(types, forKey: .types)
    }
}

