//
// LaureateResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Successful response for laureate/{ID} */
public struct LaureateResult: Codable, JSONEncodable, Hashable {

    public var laureate: Laureate?

    public init(laureate: Laureate? = nil) {
        self.laureate = laureate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case laureate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(laureate, forKey: .laureate)
    }
}

