//
// LaureatesResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Successful responses for Laureates */
public struct LaureatesResult: Codable, JSONEncodable, Hashable {

    /** Model containing a list of Laureates */
    public var laureates: [Laureate]?
    public var meta: LaureatesMeta?
    public var links: Links?

    public init(laureates: [Laureate]? = nil, meta: LaureatesMeta? = nil, links: Links? = nil) {
        self.laureates = laureates
        self.meta = meta
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case laureates
        case meta
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(laureates, forKey: .laureates)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encodeIfPresent(links, forKey: .links)
    }
}

