//
// LaureateWikipedia.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LaureateWikipedia: Codable, JSONEncodable, Hashable {

    /** Wikipedia url slug */
    public var slug: String?
    /** URL to english wikipedia page */
    public var english: String?

    public init(slug: String? = nil, english: String? = nil) {
        self.slug = slug
        self.english = english
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slug
        case english
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(english, forKey: .english)
    }
}

