//
// Links.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Links: Codable, JSONEncodable, Hashable {

    public var first: String?
    public var prev: String?
    public var _self: String?
    public var next: String?
    public var last: String?

    public init(first: String? = nil, prev: String? = nil, _self: String? = nil, next: String? = nil, last: String? = nil) {
        self.first = first
        self.prev = prev
        self._self = _self
        self.next = next
        self.last = last
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case first
        case prev
        case _self = "self"
        case next
        case last
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(first, forKey: .first)
        try container.encodeIfPresent(prev, forKey: .prev)
        try container.encodeIfPresent(_self, forKey: ._self)
        try container.encodeIfPresent(next, forKey: .next)
        try container.encodeIfPresent(last, forKey: .last)
    }
}

