//
// NobelPrizeResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Successful response for Nobel Prize search */
public struct NobelPrizeResult: Codable, JSONEncodable, Hashable {

    public var nobelPrize: NobelPrize?

    public init(nobelPrize: NobelPrize? = nil) {
        self.nobelPrize = nobelPrize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nobelPrize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nobelPrize, forKey: .nobelPrize)
    }
}

