//
// Organization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Organization: Codable, JSONEncodable, Hashable {

    public var orgName: Translation?
    public var nativeName: String?
    public var acronym: String?
    public var founded: Event?
    public var dissolution: Event?
    public var headquarters: Location?

    public init(orgName: Translation? = nil, nativeName: String? = nil, acronym: String? = nil, founded: Event? = nil, dissolution: Event? = nil, headquarters: Location? = nil) {
        self.orgName = orgName
        self.nativeName = nativeName
        self.acronym = acronym
        self.founded = founded
        self.dissolution = dissolution
        self.headquarters = headquarters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orgName
        case nativeName
        case acronym
        case founded
        case dissolution
        case headquarters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orgName, forKey: .orgName)
        try container.encodeIfPresent(nativeName, forKey: .nativeName)
        try container.encodeIfPresent(acronym, forKey: .acronym)
        try container.encodeIfPresent(founded, forKey: .founded)
        try container.encodeIfPresent(dissolution, forKey: .dissolution)
        try container.encodeIfPresent(headquarters, forKey: .headquarters)
    }
}

